### ISSUE TITLE
Add tip about loading time for web-assembly app in ADRG

### ISSUE THREAD

**Issue by rpodcast** [RConsortium/submissions-pilot4-webR#16]

**Comment by parmsam-pfizer** [comment]
Some of this is mentioned already in the first note in the `Launch Shiny Application` section of the ADRG. Not sure if you had a different note in mind.

> "If the build_app() function was used to compile the application files, you may encounter a slight delay as the web browser installs the R packages. When visiting the application in a future session, these package installations will be cached in your browser’s local storage and will render in less time."

**Comment by rpodcast** [comment]
Yup, I recall adding that in a previous revision. On a positive note, my latest testing of the bundled application only needed about 10-20 seconds before the main application rendered!
