### ISSUE TITLE
Trigger GH action to update ECTD bundle

### ISSUE THREAD

**Issue by parmsam** [RConsortium/submissions-pilot4-webR#17]
Started reviewing the ECTD repo and noticed repo needs to get updated to ensure the latest changes like the extract_app_bundle function get included. Adding this to ensure we update it before continuing our review of the repo. https://rpodcast.quarto.pub/pilot4-webassembly-adrg/#prepare-shiny-application

**Comment by parmsam-pfizer** [comment]
Tagging @rpodcast on this: https://github.com/RConsortium/submissions-pilot4-webR-to-fda

**Comment by rpodcast** [comment]
I've updated the GH action for the ECTD bundle publishing to trigger when any changes are made the the package lockfile and the utils script, in addition to the core of the app itself. The bundle has been refreshed, so I will close this now and re-open if the triggers do not perform as expected.
