### ISSUE TITLE
Error in `download.file()` in build_offline_repo.R

### ISSUE THREAD

**Issue by parmsam-pfizer** [RConsortium/submissions-pilot4-webR#2]
Lines [144](https://github.com/RConsortium/submissions-pilot4-webR/blob/main/build_offline_repo.R#L144) and [158](https://github.com/RConsortium/submissions-pilot4-webR/blob/main/build_offline_repo.R#L158) in [`build_offline_repo.R`](https://github.com/RConsortium/submissions-pilot4-webR/blob/main/build_offline_repo.R) appear to use `fs::path()` to help build the download URLs, however on Windows the URLs are changed preventing download.

Here's what they look like:
```
> path(original_repo_location, "PACKAGES.rds")
https:/repo.r-wasm.org/bin/emscripten/contrib/4.3/PACKAGES.rds
> remote_package_info <- download.file(path(original_repo_location, "PACKAGES.rds"), destfile = path(full_package_path, "PACKAGES.rds"), mode = "wb")
Error in download.file(path(original_repo_location, "PACKAGES.rds"), destfile = path(full_package_path,  : 
  scheme not supported in URL 'https:/repo.r-wasm.org/bin/emscripten/contrib/4.3/PACKAGES.rds'
```
A simple solution would be to use `file.path(original_repo_location, "PACKAGES.rds", fsep = "")`  for those lines.

**Comment by rpodcast** [comment]
I've pivoted to the new approach of having two ways of leveraging the web-assembly app (per-compiled bundle and compile on the fly). I have not encountered errors anymore with either approach, so we can close this one.
