### ISSUE TITLE
Update km-plot code to use {ggsurvfit} package

### ISSUE THREAD

**Issue by rpodcast** [RConsortium/submissions-pilot4-webR#4]
My latest testing of the application revealed that the current way we generate the km plot as seen in [these lines](https://github.com/RConsortium/submissions-pilot4-webR/blob/b7247a36e7134073f0919b4432f271cf530e20ca/app/views/km_plot.R#L110-L120) is deprecated, and the messages recommend using the [`{ggsurvfit}`](https://www.danieldsjoberg.com/ggsurvfit/) package. If someone could send a PR with the necessary updates to the code that'd be terrific.

**Comment by parmsam-pfizer** [comment]
I can take a look at this and fix it.
