### ISSUE TITLE
Concerns around size of compiled site directory

### ISSUE THREAD

**Issue by rpodcast** [RConsortium/submissions-pilot4-webR#5]
I'm continuing to assess whether we include a pre-compiled version of the web-assembly site bundle in our transfer to the FDA. I verified that the `site` directory containing the compiled site totals 92 megabytes. I'm not as well-versed in the limitations regarding the size of files sent through the eCTD gateway.

**Comment by parmsam-pfizer** [comment]
Can we compress this site directory and submit it separately? From my search online in [this PDF](https://www.fda.gov/media/135373/download), it looks like it is still under the 10 GB threshold. Maybe we can verify with our working group members from FDA.
```
M. Transmitting Electronic Submissions
The FDA Electronic Submissions Gateway (ESG)36 enables the secure submission of regulatory 
information for review and is our preferred method of transmission. For all submissions that are 
10 gigabytes (GB) or smaller, you must use the FDA ESG.
For submissions that are greater than 10 GB, refer to the FDA technical specification
Transmitting Electronic Submissions Using eCTD Specifications.
```

**Comment by parmsam-pfizer** [comment]
We already confirmed this is okay. We are not close to size limits. Can close issue.
